name: Football Fixtures Collector

on:

  # تشغيل يدوي
  workflow_dispatch:

  # تشغيل تلقائي
  schedule:

    # كل 3 ساعات
    - cron: "0 */3 * * *"


jobs:

  collect-fixtures:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Collect and update fixtures
        env:
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

        run: |
          python src/fixtures.py


          
- name: Test Telegram
  run: python src/telegram_test.py
  env:
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
