name: بيانات كرة القدم

on:
  schedule:
    - cron: "0 8,20 * * *"
  workflow_dispatch: {}

jobs:
  fetch-football-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch football data
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python football_data.py
